### ISSUE TITLE
I have never seen a turret outside

### ISSUE THREAD

**Issue by MasterEvilAce** [snaketech-tu/LCHazardsOutside#1] opened 2024-02-04 18:45 UTC
With the default config, I've never seen a single turret spawn outside, in 5+ hours of play/testing, with lots of reloading of levels.
If I increase TurretMinSpawnRate to 5 and TurretMaxSpawnRate to 10, I absolutely see turrets spawn.

I'm wondering if it's just super unlucky or if the logic is exclusive of the max value on accident? So 0 to 1 turrets is always ending up as 0 turrets. (and 0 to 2 turrets would end up in seeing either 0 or 1 turrets.)
Just a thought

**Comment by snaketech-tu** [comment] 2024-02-04 22:05
Thanks for the report! This might be due to the safe zones for turrets which results in them being deleted rather than finding a new suitable spot for them. This will be my next fix.

**Comment by snaketech-tu** [comment] 2024-02-05 22:48
I just pushed a small hotfix today that addressed several issues but I also nerfed the safety zones a bit. Turrets currently have a slightly higher spawn radius than landmines so they could spawn a bit farther off.  
The other fix promised in my previous message is still coming though. Just a heads up!

**Comment by snaketech-tu** [comment] 2024-02-14 20:58
This has been fixed in v1.1.2.  
As you presumed, this was directly caused by the max number being _excluded_ from the spawn range which caused no turrets to spawn by default. Thanks again for the report!

**Closed as completed by snaketech-tu** 2024-02-14 20:58 UTC
